version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped

    env_file:
      - ./Back/DB/.env

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Back/DB/init:/docker-entrypoint-initdb.d
      - ./Back/DB/certs/server.crt:/var/lib/postgresql/server.crt
      - ./Back/DB/certs/server.key:/var/lib/postgresql/server.key

    command: >
      postgres
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      backend_net:
        ipv4_address: 172.50.0.10


  redis:
    image: redis:latest
    container_name: redis_cache
    restart: unless-stopped

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    networks:
      backend_net:
        ipv4_address: 172.50.0.11


  server:
    build:
      context: ./Back/Server
    container_name: backend_server

    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - ./Back/Server/.env

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    networks:
      backend_net:
        ipv4_address: 172.50.0.12


volumes:
  postgres_data:
  redis_data:


networks:
  backend_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/16
