@startuml
actor User as user

participant "Server" as server
participant "Users" as users
participant "Profile" as profile
participant "Role_User" as role_user
participant "Role" as role
participant "Role_Permission" as role_permission
participant "Permissions" as permissions
participant "login_history" as login_history


user -> server: Post /register (username, email, password)
server -> server: ValidationInput(email, password)
alt Input Not Valid
    server -> user: 400 Bad Request
else Input Valid
    server -> users: findByEmail(email)
    alt Email Found
        users -> server: Email Exist
        server -> user: 404 Email Already Exist
    else Email Not Found
        server -> server: hashpassword(password)
        server -> users: Insert(email; password_hash, status='Active')
        users -> server: return (user_id)
        users -> role: Getrole('member')
        role -> users: member_id
        server -> role_user: Insert(user_id, member_id)
        role_user -> server: insert Success

        server -> user: 200, Account Created
    end

end




@enduml