@startuml
actor User as User

participant "Server" as Server
participant "Users" as Users
participant "Profile" as Profile
participant "Role_User" as Role_User
participant "Role" as Role
participant "login_history" as login_history

User -> Server: POST /register

Server -> Server: Validate input
alt Invalid
    Server -> User: 400 Bad Request
else Valid

    Server -> Server: Start Transaction

    Server -> Server: hashPassword(password)

    Server -> Users: Insert user (email UNIQUE)
    Users -> Server: return (user_id)

    alt Unique constraint error
        Server -> Server: Rollback
        Server -> User: 409 Conflict
    else Success

        Server -> Role: Get default role
        Role -> Server: Return Default Role
   
        Server -> Role_User: Insert relation (user_id, default_role)
        Role_User -> Server: Success 
        

        Server -> Profile: Create profile(user_id)
        Profile -> Server: Success

        Server -> Server: Commit

        Server -> Server: Load permissions for role
        Server -> Server: GenerateToken()

        Server -> login_history: insert(user_id, ip, device)
        login_history -> Server: Done
        
        Server -> User: 201 Created + Tokens
    end
end


@enduml